In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:

df = pd.read_csv('filtered.csv')


df.head()

,is-edible,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,s,w,w,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,s,w,w,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,s,w,w,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,s,w,w,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,s,w,w,w,o,e,n,a,g

In [16]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
for col in df.columns:
    df[col] = le.fit_transform(df[col])

df.head()

,is-edible,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,2,7,7,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,2,7,7,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,2,7,7,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,2,7,7,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,2,7,7,2,1,0,3,0,1

In [8]:

X = df.drop('is-edible', axis=1)
y = df['is-edible']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:

knn = KNeighborsClassifier(n_neighbors=3)
dt = DecisionTreeClassifier()
lr = LogisticRegression(max_iter=1000)


knn.fit(X_train, y_train)
dt.fit(X_train, y_train)
lr.fit(X_train, y_train)


y_pred_knn = knn.predict(X_test)
y_pred_dt = dt.predict(X_test)
y_pred_lr = lr.predict(X_test)

In [11]:

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("KNN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))

KNN Accuracy: 0.9981538461538462
KNN Confusion Matrix:
 [[840   3]
 [  0 782]]

In [14]:
print("dt Accuracy:", accuracy_score(y_test, y_pred_dt))
print("dt Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

dt Accuracy: 1.0
dt Confusion Matrix:
 [[843   0]
 [  0 782]]

In [15]:
print("lr Accuracy:", accuracy_score(y_test, y_pred_lr))
print("lr Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

lr Accuracy: 0.9476923076923077
lr Confusion Matrix:
 [[799  44]
 [ 41 741]]

In [12]:
from sklearn.metrics import classification_report


print("--- KNN ---")
print(classification_report(y_test, y_pred_knn))

print("--- Decision Tree ---")
print(classification_report(y_test, y_pred_dt))

print("--- Logistic Regression ---")
print(classification_report(y_test, y_pred_lr))

--- KNN ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

--- Decision Tree ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

--- Logistic Regression ---
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       843
           1       0.94      0.95      0.95       782

    accuracy                           0.95      1625
   macro avg       0.95      0.95      0.95      1625
weighted avg       0.95      0.95      0.95      1625